version: 2
jobs:
  build:
    machine: true

    working_directory: ~/app

    steps:
        
      - checkout

      - run:
          name: Install Cypress
          command: |
            set -x
            npm install cypress -g

      - run:
          name: Start containers
          command: |
            set -x
            docker-compose up -d

      - run:
          name: Running E2E tests
          command: cypress run

      # Tag master docker images
      - run: |
          TAG_MASTER=0.1.master

          USERNAME=danielesalvatore
          SERVER=e2e-testing-playground-server
          CLIENT=e2e-testing-playground-server
          
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          
          docker tag $USERNAME/$SERVER:latest $USERNAME/$SERVER:$TAG_MASTER
          docker tag $USERNAME/$CLIENT:latest $USERNAME/$CLIENT:$TAG_MASTER
          
          docker push $USERNAME/$SERVER:$TAG_MASTER 
          docker push $USERNAME/$CLIENT:$TAG_MASTER 
